# Generated by Django 6.0 on 2025-12-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_category_tag_alter_article_options_article_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
